version: '3.8'

services:
  app:
    build: .
    container_name: blog_website_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    container_name: blog_website_mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Nahush
      - MONGO_INITDB_ROOT_PASSWORD=N@hush
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
